site_name: ViT
site_url: https://uakarsh.github.io/vision-transformer
copyright: MIT
theme:
  name: "material"
  palette:
    primary: "blue"
    accent: "blue"

repo_name: uakarsh/vision-transformer
repo_url: https://github.com/uakarsh/vision-transformer


nav:
    - Home: README.md
